Rails:
  Enabled: true

Metrics/LineLength:
  Max: 180
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 25

AllCops:
  TargetRubyVersion: 2.3

Style/IndentationWidth:
  Width: 2

Style/SignalException:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Documentation:
  Enabled: false
